=== Dan13L3/mhclg-data-collection-beta/config/forms/schema/generic.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Form",
  "description": "A form",
  "type": "object",
  "properties": {
    "form_type": {
      "description": "",
      "type": "string"
    },
    "start_year": {
      "description": "",
      "type": "integer",
      "optional": "true"
    },
    "end_year": {
      "description": "",
      "type": "integer",
      "required": "false"
    },
    "sections": {
      "description": "",
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "description": "",
          "type": "string"
        },
        "label": {
          "description": "",
          "type": "string"  
        },
        "subsections": {
          "type": "object"
        }
      }
    }
  }
}

=== Dan13L3/mhclg-data-collection-beta/spec/fixtures/forms/test_form.json
{
  "form_type": "lettings",
  "start_year": 2021,
  "end_year": 2022,
  "sections": {
    "household": {
      "label": "About the household",
      "subsections": {
        "household_characteristics": {
          "label": "Household characteristics",
          "pages": {
          }
        }
      }
    }
  }
}

=== Dan13L3/mhclg-data-collection-beta/config/forms/property_information.json
{
  "form_type": "lettings",
  "start_year": 2021,
  "end_year": 2022,
  "sections": {
    "property_information": {
      "label": "Property Information",
      "subsections": {
        "about_this_log": {
          "label": "About this log",
          "pages": {
          }
        }
      }
    }
  }
}
